version: '3.0'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: e1i5
      MYSQL_ROOT_PASSWORD: 1234
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3307:3306'
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile.development
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=mysql://root:1234@localhost:3307/e1i5
      - MYSQL_CHARSET=utf8mb4
      - SALT=1
      - JWT_SECRET=????
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - ./src/:/src/
    depends_on:
      - db
